openapi: 3.0.2
info:
  version: '1.0'
  title: Taksler Sample Object
  description: Sample data for Taksler R01
  license:
    name: GNU General Public License v3 (GPL-3)
    url: >-
      https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /taksler/sample
    description: Taksler Sample Data
tags:
  - name: Taksler Sample Data
    description: Taksler Sample Data
paths:
  /getData:
    post:
      tags:
        - Taksler Sample Data
      description: Taksler Sample Data
      operationId: taksler sample data
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - age
        - sex
      properties:
        age:
          type: integer
          x-kgrid-label: Please enter your age
          x-kgrid-unit: 0
          example: 25
        sex:
          type: string
          enum:
            - Female
            - Male
          x-kgrid-label: Please select your sex at birth
          x-kgrid-unit: ''
          example: Female
    output:
      required:
        - result
      properties:
        result:
          type: array