function getData(inputs){
  return [{value: 9.5,
    title: 'Do all preventative measures',
    difficulty: 'HARD',
    description: 'Do everything  your doctor  tells you to do'},
    {value: 8.5,
      title: 'Go Skydiving',
      difficulty: 'EASY',
      description: 'Just jump out of  a moving plane'},
    {value: 6,
      title: 'Bake a cake',
      difficulty: 'MEDIUM',
      description: 'You gotta do the cooking  by the book'},
    {value: 5.2,
      title: 'Fly to England',
      difficulty: 'MEDIUM',
      description: 'pack your bags and board a plane to UK'},
    {value: 4,
      title: 'Eat a sandwich',
      difficulty: 'HARD',
      description: 'selecting the ingredients is the hardest part'},
    {value: 4,
      title: 'Learn to juggle',
      difficulty: 'EASY',
      description: 'no excuses, literally everyone can juggle'},
    {value: 3,
      title: 'Quit smoking',
      difficulty: 'HARD',
      description: 'just go cold turkey, or wear a no smoking sign'},
    {value: 2,
      title: 'Quit drinking',
      difficulty: 'MEDIUM',
      description: 'not everything, you should still drink water'},
    {value: 1,
      title: 'Join a club',
      difficulty: 'EASY',
      description: 'extreme bingo meets on wednesdays'},
    {value: 0.5,
      title: 'Take up fishing',
      difficulty: 'EASY',
      description: 'just catch and release'},
    {value: 0.33,
      title: 'Comb your hair',
      difficulty: 'HARD',
      description: 'the direction is very important'}
  ]
}

